### ISSUE TITLE
 what are the requirements

### ISSUE THREAD

**Issue by masa569** [triplej0079/DeepIM#1]
Hello, please what are the requirements

I have this issue:

/content/DeepIM/genim.py:66: DeprecationWarning: Please use `csr_matrix` from the `scipy.sparse` namespace, the `scipy.sparse.csr` namespace is deprecated.
  graph = pickle.load(f)

/content/DeepIM/genim.py:193: DeprecationWarning: Please use `csr_matrix` from the `scipy.sparse` namespace, the `scipy.sparse.csr` namespace is deprecated.
  graph = pickle.load(f)
/content/DeepIM/genim.py:188: UserWarning: Using a target size (torch.Size([1, 2810])) that is different to the input size (torch.Size([2810, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  forward_loss = F.mse_loss(y_hat, y_true)
Iteration: 1 	 Total Loss:0.85172
Iteration: 2 	 Total Loss:0.86408
/content/DeepIM/genim.py:236: DeprecationWarning: Please use `csr_matrix` from the `scipy.sparse` namespace, the `scipy.sparse.csr` namespace is deprecated.
  graph = pickle.load(f)
Traceback (most recent call last):
  File "/content/DeepIM/genim.py", line 240, in <module>
    influence = diffusion_evaluation(adj, seed, diffusion = args.diffusion_model)
  File "/content/DeepIM/main/utils.py", line 259, in diffusion_evaluation
    G = nx.from_scipy_sparse_matrix(adj_matrix)
AttributeError: module 'networkx' has no attribute 'from_scipy_sparse_matrix'

**Comment by Cosmocaoaman** [comment]
Hope this is not that late.
Just run the commend:
`pip install torch numpy scipy pandas matplotlib networkx ndlib pickle` 
 (and you can add all the libraries which is needed)

**Comment by Cosmocaoaman** [comment]
And still ,I also face the problem in line 240 and line 259
